# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: myFirstJob

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ls -l
    pwd
  displayName: 'Run a multi-line script'

- script: dotnet run -project /Users/Andre/Desktop/Development/AndreLeskinen1/AndreLeskinen1.csproj
  displayName: 'Run a console app'


  jobs:
- job: mySecondtJob

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ls -l
    pwd
  displayName: 'Run a multi-line script'

- script: dotnet run -project /Users/Andre/Desktop/Development/AndreLeskinen1/AndreLeskinen1.csproj
  displayName: 'Run a console app'
